<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_The Witcher 3 Wild Hunt - The Beginning trailer</name>
   <tag></tag>
   <elementGuidId>8d786647-1e23-4d2b-a654-f5794a124c0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.ytp-title-link.yt-uix-sessionlink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='movie_player']/div[3]/div[2]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;The Witcher 3: Wild Hunt - The Beginning trailer&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>987be412-465a-4968-8490-8abf47bd48f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ytp-title-link yt-uix-sessionlink</value>
      <webElementGuid>eb188f0d-1829-4462-8c24-b7f8d1edcee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>406a6383-041c-47c0-9caf-f658b1c9045e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sessionlink</name>
      <type>Main</type>
      <value>feature=player-title</value>
      <webElementGuid>794316d6-8c74-4289-a256-c8d4316a9737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5e924732-74cb-49a5-ae6f-aefe91af2e77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.youtube.com/watch?v=5nLipy-Z4yo</value>
      <webElementGuid>8aa48330-c6b1-48e1-8a78-aa9b20cd76eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The Witcher 3: Wild Hunt - The Beginning trailer</value>
      <webElementGuid>6babbe49-3e7e-485e-8e8a-cfa4c0a7e71c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;movie_player&quot;)/div[@class=&quot;ytp-chrome-top ytp-show-cards-title&quot;]/div[@class=&quot;ytp-title&quot;]/div[@class=&quot;ytp-title-text&quot;]/a[@class=&quot;ytp-title-link yt-uix-sessionlink&quot;]</value>
      <webElementGuid>5c29b7e3-667a-4058-b718-c3fe02645033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Game - QuestVault/iframe_Screenshots_card-img col-md-2</value>
      <webElementGuid>9993a3bb-dfc7-4f77-a07d-3614ce50e4a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='movie_player']/div[3]/div[2]/div/a</value>
      <webElementGuid>e018bd2f-000e-469e-9284-baacaca8b0b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'The Witcher 3: Wild Hunt - The Beginning trailer')]</value>
      <webElementGuid>3e53f208-6307-41c1-b57b-02258abd3c09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IGDBcom'])[2]/preceding::a[3]</value>
      <webElementGuid>554652e1-f34c-45c9-9970-e604bd9c46e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesquisa'])[1]/preceding::a[4]</value>
      <webElementGuid>11585918-48ff-4d64-98dd-b5a5b952188b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='The Witcher 3: Wild Hunt - The Beginning trailer']/parent::*</value>
      <webElementGuid>8415087f-2c63-49c0-9ee2-4b27d8f7a3f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.youtube.com/watch?v=5nLipy-Z4yo')]</value>
      <webElementGuid>fd6beccf-ba7f-4129-8fee-ced9b73a0d34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>2faa83a3-f014-442d-9cb8-25feb47dc893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.youtube.com/watch?v=5nLipy-Z4yo' and (text() = 'The Witcher 3: Wild Hunt - The Beginning trailer' or . = 'The Witcher 3: Wild Hunt - The Beginning trailer')]</value>
      <webElementGuid>1f13d034-739e-42de-ad44-2984458a25a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
