<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_The Witcher 3 Wild Hunt - Game of the Yea_879e5d</name>
   <tag></tag>
   <elementGuidId>eb3b9960-0cc0-4e3a-b7ec-9c55edbbc4b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.ytp-title-link.yt-uix-sessionlink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='movie_player']/div[3]/div[2]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>00f9336d-d675-40bb-9573-51db27dcc2d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ytp-title-link yt-uix-sessionlink</value>
      <webElementGuid>a62da8fb-053b-4322-b8d5-4b8b196a0688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>331bbb63-e208-4012-8812-82666ccf5c55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sessionlink</name>
      <type>Main</type>
      <value>feature=player-title</value>
      <webElementGuid>32b595b0-6e64-4149-920f-036bb98bbc8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>24629afb-b99e-42c4-89cb-8728d3352b5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.youtube.com/watch?v=YmLeUJgzsXY</value>
      <webElementGuid>9e82499e-0d01-4af6-83f6-e89f6325fb88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The Witcher 3: Wild Hunt - Game of the Year Edition - Launch Trailer (Official)</value>
      <webElementGuid>e3fee52e-987b-4cd1-8385-ecb0d578ae23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;movie_player&quot;)/div[@class=&quot;ytp-chrome-top ytp-show-cards-title&quot;]/div[@class=&quot;ytp-title&quot;]/div[@class=&quot;ytp-title-text&quot;]/a[@class=&quot;ytp-title-link yt-uix-sessionlink&quot;]</value>
      <webElementGuid>e32eac0f-6c9e-49da-b30e-8e435f9cca3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Game - QuestVault/iframe_Screenshots_card-img col-md-2</value>
      <webElementGuid>2828ea65-ad9c-4010-a131-7d027cbed9ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='movie_player']/div[3]/div[2]/div/a</value>
      <webElementGuid>607b7b18-af43-4519-9b12-2c046649ce15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'The Witcher 3: Wild Hunt - Game of the Year Edition - Launch Trailer (Official)')]</value>
      <webElementGuid>57cddb48-3dfc-42bc-ba1b-c5420c882506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IGDBcom'])[2]/preceding::a[3]</value>
      <webElementGuid>d533c630-3c59-4bd8-bced-06f0bd436d66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesquisa'])[1]/preceding::a[4]</value>
      <webElementGuid>164c6f66-1ed6-4f7d-9ce2-fdf21035f5a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='The Witcher 3: Wild Hunt - Game of the Year Edition - Launch Trailer (Official)']/parent::*</value>
      <webElementGuid>02aeabfb-3f9c-41be-b3b1-30a12c6311f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.youtube.com/watch?v=YmLeUJgzsXY')]</value>
      <webElementGuid>abb83ccc-fbb7-456b-ba66-0dbc71d14b6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>98ad135e-0c1c-4c3e-b69f-7655fcd67cad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.youtube.com/watch?v=YmLeUJgzsXY' and (text() = 'The Witcher 3: Wild Hunt - Game of the Year Edition - Launch Trailer (Official)' or . = 'The Witcher 3: Wild Hunt - Game of the Year Edition - Launch Trailer (Official)')]</value>
      <webElementGuid>ff58080a-738b-40ed-87b3-00ab3afc72bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
