<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5_There are no reviews yet</name>
   <tag></tag>
   <elementGuidId>f7817e00-7ddd-460f-b352-bd3342bb3f9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h5.mt-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-body']/main/div[2]/section/div[2]/h5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>09169282-63da-408e-9b2b-6c4aa93edb38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-3</value>
      <webElementGuid>65d1c20b-6bce-48a9-9497-5edc4c564d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>There are no reviews yet.</value>
      <webElementGuid>f8ebfe73-d5bc-4cf0-8c13-b8fea176f952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-body&quot;)/main[@class=&quot;pb-3&quot;]/div[@class=&quot;game-details main-section&quot;]/section[@class=&quot;container-fluid&quot;]/div[@class=&quot;d-flex justify-content-evenly&quot;]/h5[@class=&quot;mt-3&quot;]</value>
      <webElementGuid>b9cd564c-ac5c-4b45-90c3-751d31cadf3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-body']/main/div[2]/section/div[2]/h5</value>
      <webElementGuid>d80dbd37-e6c0-4535-83f3-c6d6b54224a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reviews'])[1]/following::h5[1]</value>
      <webElementGuid>937b1d86-6d7c-4a8c-94a9-8d014e371f95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/following::h5[1]</value>
      <webElementGuid>e70567b9-a3b1-4943-99eb-1ac09ac0a365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright @ 2023-2024, QuestVault. All Rights Reserved.'])[1]/preceding::h5[1]</value>
      <webElementGuid>1fb24dd4-6fbc-4f8e-8b0e-67bfab7b1237</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FAQs'])[1]/preceding::h5[1]</value>
      <webElementGuid>4061f4dc-4d29-4eab-9f20-68e724e1c61f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='There are no reviews yet.']/parent::*</value>
      <webElementGuid>c73254c5-a4bc-4ae4-9ad2-e2bc9fe66110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/h5</value>
      <webElementGuid>2114316c-4adb-40a0-b0ac-df490e16acee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[(text() = 'There are no reviews yet.' or . = 'There are no reviews yet.')]</value>
      <webElementGuid>5ec2d0d1-136d-4f32-8400-ffeb2157cfca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
