<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Screenshots_card-img col-md-2</name>
   <tag></tag>
   <elementGuidId>6a15681f-5fab-4ac6-a1ca-73a84b1ab4e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe.card-img.col-md-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>ada259bc-b76b-42f1-a031-ab0aa85e7881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-img col-md-2</value>
      <webElementGuid>47238c16-56bf-4673-94e9-8650a5fecefa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>280</value>
      <webElementGuid>8ea119ff-daf8-4d7a-a889-09a26264a17b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>318</value>
      <webElementGuid>0e3c627d-c4b0-4979-a28d-6f2f0b35537c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.youtube.com/embed/5nLipy-Z4yo</value>
      <webElementGuid>f02fc6c1-be70-4f99-83e8-a153f8d86329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>417d697e-1599-43a3-9101-7614f001602a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[1]/main[@class=&quot;pb-3&quot;]/div[@class=&quot;game-details&quot;]/section[@class=&quot;d-flex main-section&quot;]/div[@class=&quot;container-fluid justify-content-between mt-3&quot;]/div[@class=&quot;game-captures align-bottom&quot;]/iframe[@class=&quot;card-img col-md-2&quot;]</value>
      <webElementGuid>eb94a4c0-2107-4501-a051-a56ed9dec4ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>b2c4ec38-ba59-4e3f-837a-669e073961a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://www.youtube.com/embed/5nLipy-Z4yo']</value>
      <webElementGuid>82dd4d14-859d-437c-a799-c31f21d4923a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
