<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Log in_nav-vector pe-2</name>
   <tag></tag>
   <elementGuidId>39a5ab98-0850-4712-bbf0-c26e3b9da707</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.nav-vector.pe-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbarSupportedContent']/ul/li/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ef80b4a8-47cf-41c8-91d6-5c5c0c944787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>\img\vector\faKey.svg</value>
      <webElementGuid>b5a46bfa-bf33-4f6c-a119-642959904038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Key Icon</value>
      <webElementGuid>421dcfcf-de74-4464-b63b-ba1890c51318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-vector pe-2</value>
      <webElementGuid>e7da01da-7134-4f4c-9063-6e295633985e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarSupportedContent&quot;)/ul[@class=&quot;navbar-nav ms-auto me-1 mb-lg-0&quot;]/li[@class=&quot;nav-item ms-3 d-flex align-self-center&quot;]/a[@class=&quot;btn btn-primary nav-btn&quot;]/img[@class=&quot;nav-vector pe-2&quot;]</value>
      <webElementGuid>bdf4c8d8-0f58-43ba-8d7b-95e989c476de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarSupportedContent']/ul/li/a/img</value>
      <webElementGuid>5a1a7e85-f49c-4964-b6e0-cd4b9b58300e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Key Icon']</value>
      <webElementGuid>4e40c800-273f-497f-a2ea-2e1b75ca21c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a/img</value>
      <webElementGuid>690d4b22-f62e-489b-ac53-459f05e82de9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '\img\vector\faKey.svg' and @alt = 'Key Icon']</value>
      <webElementGuid>cf20c1e8-c296-4f04-8172-5a2b41c2cbed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
