<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Rating 55_icon-trash</name>
   <tag></tag>
   <elementGuidId>c3a83394-46df-4952-964c-a1a82d594186</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#icon-trash</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='icon-trash']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>444aac24-ae8c-4e69-8525-4379dfc0f9c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>icon-trash</value>
      <webElementGuid>ae8b5f32-cfb6-42c8-b400-8d3b3e32e1e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-vector</value>
      <webElementGuid>910b47bb-91c5-4a1b-99ab-361d7c7c4585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/img/vector/trash-can-solid.svg</value>
      <webElementGuid>1d475adf-6818-4524-891b-2efa5d85ea54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Trash Can Icon</value>
      <webElementGuid>36550a12-52db-4017-a318-7200d98bee30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;icon-trash&quot;)</value>
      <webElementGuid>45270f26-1e8a-4356-9e39-b0063587d8c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='icon-trash']</value>
      <webElementGuid>4a9ba886-1cf6-40fc-b57a-327b81835e02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-body']/main/div[2]/section/div[2]/div/div[3]/a/img</value>
      <webElementGuid>98995ef1-a784-4975-b6be-187d0a820310</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Trash Can Icon']</value>
      <webElementGuid>46a9f01b-2093-45d6-a0a6-794c36359878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/img</value>
      <webElementGuid>03943723-6d74-4da4-bc13-2babc2f1ba5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'icon-trash' and @src = '/img/vector/trash-can-solid.svg' and @alt = 'Trash Can Icon']</value>
      <webElementGuid>14a778cd-307a-4c94-916a-a5214be5a332</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
