<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Games_nav-vector pe-2</name>
   <tag></tag>
   <elementGuidId>2101d7e2-dd85-4fba-accb-2562dd32198a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.nav-vector.pe-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbarSupportedContent']/ul/li[3]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ca912ee9-a3d9-4917-bfa7-fefc3bce5fca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>\img\vector\gamepad.svg</value>
      <webElementGuid>30ee0ae8-f877-492a-9cbb-b35147762931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Key Icon</value>
      <webElementGuid>e5875486-e862-4254-8448-fd725afbf79f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-vector pe-2</value>
      <webElementGuid>11158a63-70cb-482d-9b8e-a0c53b9cda8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarSupportedContent&quot;)/ul[@class=&quot;navbar-nav ms-auto me-1 mb-lg-0&quot;]/li[@class=&quot;nav-item ms-3 d-flex align-self-center&quot;]/a[@class=&quot;btn btn-primary nav-btn&quot;]/img[@class=&quot;nav-vector pe-2&quot;]</value>
      <webElementGuid>28d9778c-e0fc-4071-8780-33908e35947c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarSupportedContent']/ul/li[3]/a/img</value>
      <webElementGuid>ef7845b9-6b7d-4333-ae76-2e609fbb39ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Key Icon']</value>
      <webElementGuid>3fa65c60-466d-46d2-854f-47178b633ad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/img</value>
      <webElementGuid>4f8991c2-030a-4d18-b1f0-918b83eb2867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '\img\vector\gamepad.svg' and @alt = 'Key Icon']</value>
      <webElementGuid>3256efb7-75d6-4f0c-8018-157e50fe44b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
