<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Status                              _84ebf4</name>
   <tag></tag>
   <elementGuidId>3cbc27de-fc55-4088-82e6-457c6bcb4dd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;status&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='status']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>select[name=&quot;status&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>43708faf-ee18-4b66-9fdb-8482bf205627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>(change)</name>
      <type>Main</type>
      <value>onSelected(status.value)</value>
      <webElementGuid>5dd77e91-ff59-4714-a7a1-8ad02baecf9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>ae6c7f8b-a4cf-49f6-9d34-e69f37dd617a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-results col-1 ms-2 me-2</value>
      <webElementGuid>986eb854-ffee-4eeb-8a6f-a635c2389961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Default select example</value>
      <webElementGuid>9e7141f9-9660-4dc9-aad8-92faff27960c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Status
                                    Complete
                                    Played
                                    Retired
                                    Shelved
                                    Abandoned
                                </value>
      <webElementGuid>a77926ad-5f67-4bec-9d7d-c706943148f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[1]/main[@class=&quot;pb-3&quot;]/div[@class=&quot;game-details&quot;]/section[@class=&quot;d-flex main-section&quot;]/div[@class=&quot;container ms-3 mt-4&quot;]/div[@class=&quot;ps-0&quot;]/div[@class=&quot;game-user-status&quot;]/div[@class=&quot;d-inline-flex&quot;]/form[1]/select[@class=&quot;select-results col-1 ms-2 me-2&quot;]</value>
      <webElementGuid>7d279204-25ca-4d24-90f5-8739c6183412</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='status']</value>
      <webElementGuid>c8a5a60b-e6fc-481a-8c48-9eed6780f099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adventure'])[1]/following::select[2]</value>
      <webElementGuid>2c686c38-f4cf-4dd6-9910-8ed0e1126d56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role-playing (RPG)'])[1]/following::select[2]</value>
      <webElementGuid>7121cf4f-a282-4c7b-98af-cb1205cfb76c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::select[1]</value>
      <webElementGuid>0e521bba-1b15-44ab-b3e9-c6648e7e2f1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove Game'])[1]/preceding::select[1]</value>
      <webElementGuid>6f1d81e8-c304-4bd0-8856-e04678e1ef04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[2]</value>
      <webElementGuid>8354541c-0d9f-482b-a97d-2ce6d7fdab2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'status' and (text() = '
                                    Status
                                    Complete
                                    Played
                                    Retired
                                    Shelved
                                    Abandoned
                                ' or . = '
                                    Status
                                    Complete
                                    Played
                                    Retired
                                    Shelved
                                    Abandoned
                                ')]</value>
      <webElementGuid>821819bb-824e-4db2-a8a2-4d137d0dae48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
