<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__reviewV</name>
   <tag></tag>
   <elementGuidId>2b877873-9787-48d8-b81c-e0b115ebcd11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reviewV</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='reviewV']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Write your review here (max 255)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>691bf4f2-aed8-4a81-9b08-3db32bde2af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reviewV</value>
      <webElementGuid>61fd0cc3-70b2-4bbf-8483-6f1c6ca98f5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reviewV</value>
      <webElementGuid>611e5a67-6a84-4d91-a599-9a5e49c88841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>bc4c675e-cc70-4d9d-95a6-03b4f7865335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Write your review here (max 255)</value>
      <webElementGuid>7a0bf188-f41e-4f38-9d20-a41641cd3a3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reviewV&quot;)</value>
      <webElementGuid>10fbb3ea-295d-430c-848e-19ed2a7d2722</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='reviewV']</value>
      <webElementGuid>41d14f8b-fb4d-4802-8020-4cf65443e68f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>cec1ff5a-43fc-4da9-bd79-d6693063be48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'reviewV' and @id = 'reviewV' and @placeholder = 'Write your review here (max 255)']</value>
      <webElementGuid>01838185-8021-4d9e-a1c8-e2b456f6e85f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
