<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>video_PT_video-stream html5-main-video</name>
   <tag></tag>
   <elementGuidId>00bc8f1a-9925-4f59-a9db-302afd108b15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>video.video-stream.html5-main-video</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='movie_player']/div/video</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>video</value>
      <webElementGuid>4f9a4f67-9bc4-49a0-9f2e-d9814b6ea886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>39011f8b-fcf4-4694-bc6e-3a4a0d139ef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>video-stream html5-main-video</value>
      <webElementGuid>ed929378-42af-46be-9a44-aa3bd30b2d4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>controlslist</name>
      <type>Main</type>
      <value>nodownload</value>
      <webElementGuid>6e80d5e7-a46d-4347-b747-a2249a58262e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>blob:https://www.youtube.com/d35b5240-f09c-482c-a979-aaacc7d66909</value>
      <webElementGuid>6b2b2fb8-34c9-4106-b9c9-5a423c403364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;movie_player&quot;)/div[@class=&quot;html5-video-container&quot;]/video[@class=&quot;video-stream html5-main-video&quot;]</value>
      <webElementGuid>cca0f982-9d42-4789-9484-e750bba0d7b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='movie_player']/div/video</value>
      <webElementGuid>9422abfa-221c-4284-8426-792250cdd3fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//video</value>
      <webElementGuid>7afa600b-3138-4881-b5ad-4394ce991b29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//video[@src = 'blob:https://www.youtube.com/d35b5240-f09c-482c-a979-aaacc7d66909']</value>
      <webElementGuid>639e8f7b-2253-4c12-a87f-6b4c063dcbf9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
