<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>yt-formatted-string_The Witcher 3 Wild Hunt_9cf09b</name>
   <tag></tag>
   <elementGuidId>bba58c5e-e61e-4c8e-82a0-746b822c573f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>yt-formatted-string.style-scope.ytd-watch-metadata</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='title']/h1/yt-formatted-string</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>yt-formatted-string</value>
      <webElementGuid>c5a98efc-1448-4ded-98b7-e54391975acd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style-scope ytd-watch-metadata</value>
      <webElementGuid>5c2156b7-2979-4516-9638-0d9a754ec230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The Witcher 3: Wild Hunt - Game of the Year Edition - Launch Trailer (Official)</value>
      <webElementGuid>c94e0a29-bcb1-464f-9862-393cba5fee6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;above-the-fold&quot;)/div[@id=&quot;title&quot;]/h1[@class=&quot;style-scope ytd-watch-metadata&quot;]/yt-formatted-string[@class=&quot;style-scope ytd-watch-metadata&quot;]</value>
      <webElementGuid>e01f4618-8a36-486f-9fb0-8d3247890b8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='title']/h1/yt-formatted-string</value>
      <webElementGuid>0f94547f-7cb1-4e82-a8ac-c5f70b6f14db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desloque para ver mais informações.'])[1]/following::yt-formatted-string[1]</value>
      <webElementGuid>1d747e07-0431-44db-bb4c-84663c146fc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Em direto'])[2]/following::yt-formatted-string[1]</value>
      <webElementGuid>8c761148-3cd9-4121-8602-a5a78385f4d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IGDBcom'])[2]/preceding::yt-formatted-string[1]</value>
      <webElementGuid>b311a21c-22a0-4a45-ba94-ed376007331d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/yt-formatted-string</value>
      <webElementGuid>91178b41-692a-45cf-9ab5-4d3b358d20f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//yt-formatted-string[(text() = 'The Witcher 3: Wild Hunt - Game of the Year Edition - Launch Trailer (Official)' or . = 'The Witcher 3: Wild Hunt - Game of the Year Edition - Launch Trailer (Official)')]</value>
      <webElementGuid>fff1d155-d7e8-4c03-a7f0-aae1967a6090</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
