<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>f026cd03-a931-4ad7-bcab-176c6425e594</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.game-button > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-body']/main/div/div[2]/div[2]/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link >> nth=4</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>27e50f22-65ab-473b-b7da-fa9fb8622755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//images.igdb.com/igdb/image/upload/t_cover_big/co1rbi.jpg</value>
      <webElementGuid>559bfd40-3d94-40de-9333-e3aa361772e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-body&quot;)/main[@class=&quot;pb-3&quot;]/div[@class=&quot;main-section&quot;]/div[@class=&quot;d-flex main-section-result&quot;]/div[@class=&quot;game-section&quot;]/div[@class=&quot;game-row&quot;]/a[@class=&quot;game-button&quot;]/img[1]</value>
      <webElementGuid>9b53fe0b-9f9e-4291-ac4a-144de9f7cd66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-body']/main/div/div[2]/div[2]/div/a/img</value>
      <webElementGuid>87f3b14d-1530-40bc-86c9-17916520cb4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/img</value>
      <webElementGuid>e0b3aacf-3af1-4ab0-b9e4-4d18622373d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//images.igdb.com/igdb/image/upload/t_cover_big/co1rbi.jpg']</value>
      <webElementGuid>3678e9d2-c070-47dd-9dc7-caab723ad482</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
