<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_MyLibrary_mb-1</name>
   <tag></tag>
   <elementGuidId>781508a4-ec8c-40db-9eba-4da7a3bf7bae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.mb-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbarSupportedContent']/ul/li[5]/div/button/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c6e9b4dd-0d0a-4bbb-9672-0e8f6aef10ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/img/usr_profile/cd6d589c-8a70-4dea-8dc2-a4ef9f4cbaec_pa.jpg</value>
      <webElementGuid>6b7b7b30-3135-4028-8e76-31e0c0b93f0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Key Icon</value>
      <webElementGuid>ffe801d9-2926-405d-b194-8125c0247548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-1</value>
      <webElementGuid>a15dd2b6-db80-4dff-a0a1-580a4a06f75f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarSupportedContent&quot;)/ul[@class=&quot;navbar-nav ms-auto me-1 mb-lg-0&quot;]/li[@class=&quot;nav-item ms-3 d-flex align-self-center&quot;]/div[@class=&quot;dropdown&quot;]/button[@class=&quot;btn btn-primary nav-btn show&quot;]/img[@class=&quot;mb-1&quot;]</value>
      <webElementGuid>8d3423a2-5c0e-4f12-842c-81f73ace4e52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarSupportedContent']/ul/li[5]/div/button/img</value>
      <webElementGuid>06230a8c-c4c1-4b82-94ea-27ab4197379a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Key Icon'])[2]</value>
      <webElementGuid>af0dedc5-6841-4e36-99ca-d379e71f1227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div/button/img</value>
      <webElementGuid>d699097d-5c52-458a-bd64-c7c2b853b445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/img/usr_profile/cd6d589c-8a70-4dea-8dc2-a4ef9f4cbaec_pa.jpg' and @alt = 'Key Icon']</value>
      <webElementGuid>a2104a5f-0c70-4d15-a059-b3a0137f7ddc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
