<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Insert Steam Id_steamId</name>
   <tag></tag>
   <elementGuidId>303c2b1e-ef5a-4e8d-b58b-3b78c1618dca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#steamId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='steamId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d6be7550-a930-479f-b94c-d8e95bd8e054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2aee7da0-5d7e-4005-aea1-8878e5b54b09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-purple</value>
      <webElementGuid>9d30ef4d-3992-481b-ab44-bd26daead78e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Steam Id</value>
      <webElementGuid>2658ca58-4ddb-4b5f-ad14-1f3ecdb7c18f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>steamId</value>
      <webElementGuid>9505483a-ab93-4db8-ab64-c6dff073913d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>steamId</value>
      <webElementGuid>a83dc63a-079e-4098-ac71-73b8fd88b419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;steamId&quot;)</value>
      <webElementGuid>4c114200-9d9f-4784-9775-346c0afdb780</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='steamId']</value>
      <webElementGuid>5ac584ab-811a-4d4f-a3e2-e51551885f96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='steamForm']/div/div/div/div[2]/input</value>
      <webElementGuid>22fce103-a078-4b38-b87d-0011e0c2bf22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>78d7784f-b580-4062-9bf8-fd3db0b6b760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Steam Id' and @id = 'steamId' and @name = 'steamId']</value>
      <webElementGuid>086e706e-2765-4c6d-a132-b7df52d18232</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
