<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Log in_row-login</name>
   <tag></tag>
   <elementGuidId>877e68d9-0314-4e40-8995-001d14e026e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.row-login</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='account']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bc75909b-8da4-49f0-afed-b57d638cbb15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row-login</value>
      <webElementGuid>31005a78-fa27-40e7-9cc9-d3b69efce0f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;account&quot;)/div[@class=&quot;row-login&quot;]</value>
      <webElementGuid>6ac2a669-bcdd-4ac8-98fa-d780154f75b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='account']/div</value>
      <webElementGuid>1f6a8522-bbce-4c31-bf36-fe1f004f6ea7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[1]/following::div[1]</value>
      <webElementGuid>2e6bc8d7-5e11-49af-a89d-7f932fa77153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[2]/preceding::div[4]</value>
      <webElementGuid>d7f5b24c-878b-4faa-9ac8-270cdf456317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div</value>
      <webElementGuid>f331112d-c2da-42ff-872b-8b2f7398d251</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
