<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Team Fortress 2</name>
   <tag></tag>
   <elementGuidId>4b021679-9c6a-4cd8-8acd-0c15d4a6cefc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#appHubAppName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='appHubAppName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>49027d0d-c130-4ac1-8504-e848d68aa069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>appHubAppName</value>
      <webElementGuid>82f31045-f1db-4125-94ce-dc95a3800c8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>apphub_AppName</value>
      <webElementGuid>bc504075-44b5-4268-859d-124806ef2d69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Team Fortress 2</value>
      <webElementGuid>384d2891-553c-48d7-a11d-56adf59a7080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appHubAppName&quot;)</value>
      <webElementGuid>26a4e293-bc28-4eea-9872-e2f0bfdd73f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='appHubAppName']</value>
      <webElementGuid>897107c4-e307-488c-906a-76f1ec823da2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabletGrid']/div/div[2]/div[2]/div/div[3]</value>
      <webElementGuid>576173c0-89bb-40c3-9ed2-5bfa2095d08a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Central Comunitária'])[1]/following::div[3]</value>
      <webElementGuid>921daf5e-7e3d-4e93-90d2-10578bd2b231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Team Fortress 2'])[1]/following::div[7]</value>
      <webElementGuid>ec4e40c6-30b3-48fe-87e2-be9827be60fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Team Fortress 2'])[3]/preceding::div[4]</value>
      <webElementGuid>59e3e4b3-7034-45d2-9928-312c6f1a3547</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Developer'])[1]/preceding::div[5]</value>
      <webElementGuid>5f2e3326-49d3-4eae-8ab2-362ed8f84cde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[2]/div/div[3]</value>
      <webElementGuid>9c9bcd89-23e6-4b09-9178-1aff8df6818d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'appHubAppName' and (text() = 'Team Fortress 2' or . = 'Team Fortress 2')]</value>
      <webElementGuid>1638d54f-f62d-4c59-92df-845c3cc23235</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
