<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>fd04e185-8326-413a-a3bc-957325e28047</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Link para a página inicial do Steam&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='logo_holder']/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7bfca821-59cc-46f2-bdc8-6b13f9053137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://store.cloudflare.steamstatic.com/public/shared/images/header/logo_steam.svg?t=962016</value>
      <webElementGuid>612a4ea7-0deb-4626-afa0-2f6f1a3c6067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>176</value>
      <webElementGuid>c19f5465-b6d5-4957-ad86-20bbbcf5a972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>44</value>
      <webElementGuid>f75ed5b5-4732-48b1-bd08-7ea5bff0a9d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Link para a página inicial do Steam</value>
      <webElementGuid>029fe69c-3e73-45f4-85f0-29179242599b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logo_holder&quot;)/a[1]/img[1]</value>
      <webElementGuid>83e1d8bb-fab5-4289-bab9-e1ae864900f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='logo_holder']/a/img</value>
      <webElementGuid>ff15546f-4058-44b0-8780-13942a009b80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Link para a página inicial do Steam']</value>
      <webElementGuid>cb23eb0a-6829-4e2b-be5a-0fe12911fd35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a/img</value>
      <webElementGuid>a67d1c63-2097-4294-b07e-aa21703fe14a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://store.cloudflare.steamstatic.com/public/shared/images/header/logo_steam.svg?t=962016' and @alt = 'Link para a página inicial do Steam']</value>
      <webElementGuid>605c4d98-0d4d-4daa-a4d1-6a5ed06e1eab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
