<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>0e9bc175-b57c-4e06-a862-5d48e83fd812</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.game-button > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.game-button >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6edc1363-bd85-4b4d-b0ef-5cbed7377e38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//images.igdb.com/igdb/image/upload/t_cover_big/co1wyy.jpg</value>
      <webElementGuid>a4dbcc35-7a3f-4721-af2e-a2484e891f3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[1]/main[@class=&quot;pb-3&quot;]/div[@class=&quot;results-game&quot;]/div[@class=&quot;d-flex main-section-result&quot;]/div[@class=&quot;game-section&quot;]/div[@class=&quot;game-row&quot;]/a[@class=&quot;game-button&quot;]/img[1]</value>
      <webElementGuid>dbfffbac-bc93-4c2c-9400-fde3c4b0ac89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/img</value>
      <webElementGuid>47353c69-c014-49ca-b910-8ca3c3c5f6fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//images.igdb.com/igdb/image/upload/t_cover_big/co1wyy.jpg']</value>
      <webElementGuid>9128e7c0-e3b2-41f5-a80a-a51be5723443</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
