<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Users_nav-vector pe-1</name>
   <tag></tag>
   <elementGuidId>0a2a509d-c253-4adc-9462-87a51fa16ae5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-purple.btn-users-inverted.align-items-center.m-2 > img.nav-vector.pe-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-body']/main/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b31a71dd-f3b4-47a9-bb24-33ffda825a5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-vector pe-1</value>
      <webElementGuid>37044f20-7b02-4a30-bd42-a00c980262fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/img/vector/user.svg</value>
      <webElementGuid>92cf0138-a698-49a5-8635-f5b3dccaa688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>User Icon</value>
      <webElementGuid>4d43f210-2dea-419a-8b9c-f5d9b105a972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-body&quot;)/main[@class=&quot;pb-3&quot;]/div[@class=&quot;main-section&quot;]/div[@class=&quot;d-flex justify-content-center&quot;]/a[@class=&quot;btn btn-purple btn-users-inverted align-items-center m-2&quot;]/img[@class=&quot;nav-vector pe-1&quot;]</value>
      <webElementGuid>c75f2b7f-87e9-42f7-aa4d-477793902c2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-body']/main/div/div/a/img</value>
      <webElementGuid>67b1f5e2-79e0-40a2-91ed-e385e244da79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='User Icon']</value>
      <webElementGuid>a0b9845a-e97f-4a56-a23b-442ae6b260dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a/img</value>
      <webElementGuid>904ff741-f02b-45f8-8d78-e2be7eb7df36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/img/vector/user.svg' and @alt = 'User Icon']</value>
      <webElementGuid>0ea1f5ac-4abb-42dc-832e-5256d1b92baf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
