<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Grand Theft Auto V</name>
   <tag></tag>
   <elementGuidId>86f216ed-69de-45c2-acf0-87da0de55f32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='searchResults']/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Grand Theft Auto V&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fd556a9a-5f51-47bd-b531-079d1494f368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Games/Details/1020</value>
      <webElementGuid>e6ea8e48-7434-4685-812e-ceb0f97d130c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Grand Theft Auto V</value>
      <webElementGuid>0fb072ab-da76-4072-883b-f8cabf20ca26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchResults&quot;)/li[@class=&quot;list-group-item&quot;]/a[1]</value>
      <webElementGuid>38e7ab47-a794-4232-a805-ebb1bd0693fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='searchResults']/li[2]/a</value>
      <webElementGuid>53cc75b9-6d44-4da5-8712-98a445f6fe3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Grand Theft Auto V')]</value>
      <webElementGuid>31e6401f-4224-40e3-9c51-66d4a443b8db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grand Theft Auto: San Andreas'])[1]/following::a[1]</value>
      <webElementGuid>59dc02d5-4953-4b58-9b36-acc52764acee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Grand Theft Auto V']/parent::*</value>
      <webElementGuid>6e2ccf4b-5b2b-4920-830c-9e5cd58deb44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Games/Details/1020')]</value>
      <webElementGuid>bd6e7836-d061-4b80-a9fc-4d7fabe0a942</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>90357be0-b69c-4033-81b5-2e3e6cb0e605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Games/Details/1020' and (text() = 'Grand Theft Auto V' or . = 'Grand Theft Auto V')]</value>
      <webElementGuid>238c904b-1b01-4c75-a9d3-930a8ed53646</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
