<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Games_search-btn</name>
   <tag></tag>
   <elementGuidId>9c3b791e-b182-4c61-8712-f404903097c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@src = '\img\vector\magnifying.svg']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.search-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='search']/form/div/button/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#search >> internal:role=button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>442e2ed6-8604-4c8d-a4f1-54a20e54f2f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>\img\vector\magnifying.svg</value>
      <webElementGuid>3862f874-c1a2-47b2-b9ae-a9f184b3df4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-btn</value>
      <webElementGuid>073f01d7-7dfe-4854-a605-971028a258bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search&quot;)/form[1]/div[@class=&quot;search-bar d-flex&quot;]/button[@class=&quot;outside-search&quot;]/img[@class=&quot;search-btn&quot;]</value>
      <webElementGuid>49b7ee96-a81e-4ccb-8d96-1aad2d12902f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='search']/form/div/button/img</value>
      <webElementGuid>4f58e877-9e23-4106-bb1b-0aa4c14a6dc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>33de9853-132a-47fc-80f1-d0fe1905450a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '\img\vector\magnifying.svg']</value>
      <webElementGuid>e86235f2-ee6f-4ccf-855f-5c4fb8691e31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
