<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Games_search-btn</name>
   <tag></tag>
   <elementGuidId>9c3b791e-b182-4c61-8712-f404903097c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.search-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#search >> internal:role=button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c647ee57-a751-477d-aa00-3bad7f0ffb16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>\img\vector\magnifying.svg</value>
      <webElementGuid>9aadc440-0926-4aec-94b4-c3833b54faba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-btn</value>
      <webElementGuid>b716a49f-d7c2-41ff-acdf-5bb2ac1ca18d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search&quot;)/form[1]/div[@class=&quot;search-bar d-flex&quot;]/button[@class=&quot;outside-search&quot;]/img[@class=&quot;search-btn&quot;]</value>
      <webElementGuid>eac820d3-2afb-483e-8297-4c7cc45ee90c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='search']/form/div/button/img</value>
      <webElementGuid>e60a3998-ba40-4d82-8f8c-00ac2156072d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>da90cd2a-c20f-4b2e-b635-5f0fbc0fe8a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '\img\vector\magnifying.svg']</value>
      <webElementGuid>b325635c-06c4-467c-b872-539c8d072303</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
