<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_Top 5 Genres_topGenresChart</name>
   <tag></tag>
   <elementGuidId>66e13c02-0df3-4391-9644-e9fd90ee2fb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#topGenresChart</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//canvas[@id='topGenresChart']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>35072a52-eab3-4e19-8da2-145b266dd3a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>topGenresChart</value>
      <webElementGuid>0e60c681-594c-4ff8-a6f4-0dbc955dfb9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>480</value>
      <webElementGuid>767a2304-1186-468b-ac69-fe6ba2356faf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>480</value>
      <webElementGuid>7bcb59cb-1498-43ce-8953-843d2cca1af3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topGenresChart&quot;)</value>
      <webElementGuid>74d6dbdf-eaec-4256-a5e5-8d74d639ac00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='topGenresChart']</value>
      <webElementGuid>1c49ac84-423a-4260-beab-52a652ddc601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-body']/main/div/div[2]/div[2]/div[2]/canvas</value>
      <webElementGuid>e06dbd8b-0b35-42aa-896f-0feac52d453a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/canvas</value>
      <webElementGuid>9e2b432f-5bbf-430b-a077-a00118f2a06d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//canvas[@id = 'topGenresChart']</value>
      <webElementGuid>cb724fd9-9927-4633-8159-c8b526e794d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
