<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Registered Accounts</name>
   <tag></tag>
   <elementGuidId>506307d1-1f45-4a9d-9f1b-dc179181a225</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h4.mt-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-body']/main/div/div[2]/div/div/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>04dd6eeb-8193-4543-9f99-772cc6e7c57e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-2</value>
      <webElementGuid>085fe2a7-2e16-4be0-a20e-2e8502a4dd50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Registered Accounts </value>
      <webElementGuid>030eb733-3bcc-4bd4-8a68-be499b915120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-body&quot;)/main[@class=&quot;pb-3&quot;]/div[@class=&quot;main-section&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;main-section-title container d-flex justify-content-between align-items-end m-0&quot;]/div[@class=&quot;d-inline-flex align-items-center&quot;]/h4[@class=&quot;mt-2&quot;]</value>
      <webElementGuid>4a91abb8-3354-45ee-b5b7-eb192cc16934</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-body']/main/div/div[2]/div/div/h4</value>
      <webElementGuid>012d6ab0-ae5f-4043-8ee7-6ebcdc3c3700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='App Stats'])[1]/following::h4[1]</value>
      <webElementGuid>6bb48e88-7ceb-4ff2-a074-57bf769e3e65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::h4[1]</value>
      <webElementGuid>2b094097-8e4d-4a64-95d6-939dc54adb78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Average Game Rating'])[1]/preceding::h4[1]</value>
      <webElementGuid>07626668-c00a-4592-ba21-1f8b0eb75222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daily Logins'])[1]/preceding::h4[2]</value>
      <webElementGuid>ed4bb5c5-9f43-42ed-8220-7cbb6c7b70e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Registered Accounts']/parent::*</value>
      <webElementGuid>ee10fcd5-4519-4dfd-9e23-4422d07e729d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>af96d086-2e92-44aa-a985-70df001345f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Registered Accounts ' or . = 'Registered Accounts ')]</value>
      <webElementGuid>8834d82b-0d45-4eae-85a5-2978db23baf6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
