// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using questvault.Data;

#nullable disable

namespace questvault.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240311174350_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("questvault.Models.Company", b =>
                {
                    b.Property<int>("CompanyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyID"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyID");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("questvault.Models.Games", b =>
                {
                    b.Property<int>("GameID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameID"));

                    b.Property<int?>("CompanyID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlatformID")
                        .HasColumnType("int");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("PlatformID");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameID = 1020,
                            Name = "Grand Theft Auto V",
                            Rating = 89.820437867083484,
                            Summary = "Grand Theft Auto V is a vast open world game set in Los Santos, a sprawling sun-soaked metropolis struggling to stay afloat in an era of economic uncertainty and cheap reality TV. The game blends storytelling and gameplay in new ways as players repeatedly jump in and out of the lives of the game’s three lead characters, playing all sides of the game’s interwoven story."
                        },
                        new
                        {
                            GameID = 1942,
                            Name = "The Witcher 3: Wild Hunt",
                            Rating = 94.145586486610682,
                            Summary = "RPG and sequel to The Witcher 2 (2011), The Witcher 3 follows witcher Geralt of Rivia as he seeks out his former lover and his young subject while intermingling with the political workings of the wartorn Northern Kingdoms. Geralt has to fight monsters and deal with people of all sorts in order to solve complex problems and settle contentious disputes, each ranging from the personal to the world-changing."
                        },
                        new
                        {
                            GameID = 72,
                            Name = "Portal 2",
                            Rating = 91.850130392615029,
                            Summary = "Sequel to the acclaimed Portal (2007), Portal 2 pits the protagonist of the original game, Chell, and her new robot friend, Wheatley, against more puzzles conceived by GLaDOS, an A.I. with the sole purpose of testing the Portal Gun's mechanics and taking revenge on Chell for the events of Portal. As a result of several interactions and revelations, Chell once again pushes to escape Aperture Science Labs."
                        },
                        new
                        {
                            GameID = 472,
                            Name = "The Elder Scrolls V: Skyrim",
                            Rating = 87.69369540690036,
                            Summary = "Skyrim reimagines and revolutionizes the open-world fantasy epic, bringing to life a complete virtual world open for you to explore any way you choose. Play any type of character you can imagine, and do whatever you want; the legendary freedom of choice, storytelling, and adventure of The Elder Scrolls is realized like never before."
                        },
                        new
                        {
                            GameID = 71,
                            Name = "Portal",
                            Rating = 86.777775518353337,
                            Summary = "Waking up in a seemingly empty laboratory, the player is made to complete various physics-based puzzle challenges through numerous test chambers in order to test out the new Aperture Science Handheld Portal Device, without an explanation as to how, why or by whom."
                        },
                        new
                        {
                            GameID = 732,
                            Name = "Grand Theft Auto: San Andreas",
                            Rating = 90.589305216088775,
                            Summary = "Returning after his mother's murder to the semi-fictional city of Los Santos (based on Los Angeles), Carl Johnson, a former gang banger, must take back the streets for his family and friends by gaining respect and once again gaining control over the streets. However, a story filled with crime, lies and corruption will lead him to trudge the entire state of San Andreas (based on California and Nevada) to rebuild his life."
                        },
                        new
                        {
                            GameID = 233,
                            Name = "Half-Life 2",
                            Rating = 90.659032917457338,
                            Summary = "1998. HALF-LIFE sends a shock through the game industry with its combination of pounding action and continuous, immersive storytelling.\n\nNOW. By taking the suspense, challenge and visceral charge of the original, and adding startling new realism and responsiveness, Half-Life 2 opens the door to a world where the player's presence affects everything around them, from the physical environment to the behaviors even the emotions of both friends and enemies."
                        },
                        new
                        {
                            GameID = 1009,
                            Name = "The Last of Us",
                            Rating = 93.352240521857155,
                            Summary = "A third person shooter/stealth/survival hybrid, in which twenty years after the outbreak of a parasitic fungus which takes over the neural functions of humans, Joel, a Texan with a tragic familial past, finds himself responsible with smuggling a fourteen year old girl named Ellie to a militia group called the Fireflies, while avoiding strict and deadly authorities, infected fungal hosts and other violent survivors."
                        },
                        new
                        {
                            GameID = 20,
                            Name = "BioShock",
                            Rating = 86.739828401883614,
                            Summary = "BioShock is a horror-themed first-person shooter set in a steampunk underwater dystopia. The player is urged to turn everything into a weapon: biologically modifying their own body with Plasmids, hacking devices and systems, upgrading their weapons, crafting new ammo variants, and experimenting with different battle techniques are all possible. The game is described by the developers as a spiritual successor to their previous PC title System Shock 2. BioShock received high praise in critical reviews for its atmospheric audio and visual quality, absorbing and original plot and its unique gaming experience."
                        },
                        new
                        {
                            GameID = 127,
                            Name = "Assassin's Creed II",
                            Rating = 86.917321771555009,
                            Summary = "Discover an intriguing and epic story of power, revenge and conspiracy set during a pivotal moment in history: the Italian Renaissance.\nExperience the freedom and immersion of an all new open world and mission structure with settings such as the rooftops and canals of beautiful Venice. Your options in combat, assassination and escape are vast, with many new weapons, settings and gameplay elements."
                        },
                        new
                        {
                            GameID = 733,
                            Name = "Grand Theft Auto: Vice City",
                            Rating = 87.668782476460905,
                            Summary = "In the year 1986, Tommy Vercetti is heavily indebted to his mafia superiors after a drug deal gone awry, but his dreams of taking over Vice City (based on Miami) push him down a different path. Featuring a wide variety of vehicles and weapons, radio stations playing hit songs from the era and an intense atmosphere, GTA: Vice City is an open-world sandbox satire of '80's Miami."
                        },
                        new
                        {
                            GameID = 19560,
                            Name = "God of War",
                            Rating = 93.497378259827357,
                            Summary = "God of War is the sequel to God of War III as well as a continuation of the canon God of War chronology. Unlike previous installments, this game focuses on Norse mythology and follows an older and more seasoned Kratos and his son Atreus in the years since the third game. It is in this harsh, unforgiving world that he must fight to survive… and teach his son to do the same."
                        },
                        new
                        {
                            GameID = 538,
                            Name = "BioShock Infinite",
                            Rating = 85.802211114776952,
                            Summary = "BioShock Infinite is the third game in the BioShock series. It is not a direct sequel/prequel to any of the previous BioShock games but takes place in an entirely different setting, although it shares similar features, gameplay and concepts with the previous games. BioShock Infinite features a range of environments that force the player to adapt, with different weapons and strategies for each situation. Interior spaces feature close combat with enemies, but unlike previous games set in Rapture, the setting of Infinite contains open spaces with emphasis on sniping and ranged combat against as many as fifteen enemies at once."
                        },
                        new
                        {
                            GameID = 74,
                            Name = "Mass Effect 2",
                            Rating = 91.338660325704438,
                            Summary = "Are you prepared to lose everything to save the galaxy? You'll need to be, Commander Shephard. It's time to bring together your greatest allies and recruit the galaxy's fighting elite to continue the resistance against the invading Reapers. So steel yourself, because this is an astronomical mission where sacrifices must be made. You'll face tougher choices and new, deadlier enemies. Arm yourself and prepare for an unforgettable intergalactic adventure.\n\nGame Features:\n\nShift the fight in your favour. Equip yourself with powerful new weapons almost instantly thanks to a new inventory system. Plus, an improved health regeneration system means you'll spend less time hunting for restorative items.\n\nMake every decision matter. Divisive crew members are just the tip of the iceberg, Commander, because you'll also be tasked with issues of intergalactic diplomacy. And time's a wastin' so don't be afraid to use new prompt-based actions that let you interrupt conversations, even if they could alter the fate of your crew...and the galaxy.\n\nForge new alliances, carefully. You'll fight alongside some of your most trustworthy crew members, but you'll also get the opportunity to recruit new talent. Just choose your new partners with care because the fate of the galaxy rests on your shoulders, Commander."
                        },
                        new
                        {
                            GameID = 231,
                            Name = "Half-Life",
                            Rating = 88.785089339294046,
                            Summary = "Dr. Gordon Freeman doesn't speak, but he's got a helluva story to tell. This first-person roller-coaster initiated a new era in the history of action games by combining engrossing gameplay, upgraded graphics, ingenious level design and a revolutionary story that may not be all that it seems, told not through cutscenes, but through the visual environment."
                        },
                        new
                        {
                            GameID = 500,
                            Name = "Batman: Arkham Asylum",
                            Rating = 85.921804117204573,
                            Summary = "Using a great variety of gadgets you must make your way around the island, and the asylums halls to find and stop the joker. The game uses a 3-button combat system, but with a great number of gadget abilites which Batman can unlock. This makes for a very cinematic combat experience when fighting the Joker's goons."
                        },
                        new
                        {
                            GameID = 7346,
                            Name = "The Legend of Zelda: Breath of the Wild",
                            Rating = 92.797742524418041,
                            Summary = "The Legend of Zelda: Breath of the Wild is the first 3D open-world game in the Zelda series. Link can travel anywhere and be equipped with weapons and armor found throughout the world to grant him various bonuses. Unlike many games in the series, Breath of the Wild does not impose a specific order in which quests or dungeons must be completed. While the game still has environmental obstacles such as weather effects, inhospitable lands, or powerful enemies, many of them can be overcome using the right method. A lot of critics ranked Breath of the Wild as one of the best video games of all time."
                        },
                        new
                        {
                            GameID = 25076,
                            Name = "Red Dead Redemption 2",
                            Rating = 92.518490744523689,
                            Summary = "Red Dead Redemption 2 is the epic tale of outlaw Arthur Morgan and the infamous Van der Linde gang, on the run across America at the dawn of the modern age."
                        },
                        new
                        {
                            GameID = 73,
                            Name = "Mass Effect",
                            Rating = 86.295074852037885,
                            Summary = "What starts as a routine mission to an agrarian outpost quickly becomes the opening salvo in an epic war. As the newly appointed Executive Officer of the SSV Normandy, you'll assemble and lead an elite squad of heroes into battle after heart-pounding battle. Each decision you make will impact not only your fate, but the destiny of the entire galaxy in the Mass Effect trilogy.\n\nKey Features:\n\nIncredible, interactive storytelling. Create and customize your own character, from Commander Shepard's appearance and skills to a personalized arsenal. Unleash devastating abilities as you command and train. Your decisions will control the outcome of each mission, your relationships with your crew and ultimately the entire war.\n\nAn amazing universe to explore. From the massive Citadel to the harsh, radioactive landscape of the Krogan home world – the incredible breadth of the Mass Effect universe will blow you away. Travel to the farthest outposts aboard the SSV Normandy, the most technologically advanced ship in the galaxy. You'll follow the clues left by ancient civilizations, discover hidden bases with fantastic new tech and lead your hand-picked crew into explosive alien battles.\n\nEdge-of-your-seat excitement meets strategic combat. Find the perfect combination of squad-mates and weapons for each battle if you want to lead them to victory. Sun-Tzu's advice remains as pertinent in 2183 as it is today – know your enemy. You'll need different tactics for a squad of enemies with devastating biotic attacks than a heavily armored Geth Colossus so choose your teams wisely."
                        },
                        new
                        {
                            GameID = 501,
                            Name = "Batman: Arkham City",
                            Rating = 87.261028920393471,
                            Summary = "Batman: Arkham City builds upon the intense, atmospheric foundation of Batman: Arkham Asylum, sending players soaring into Arkham City, the new maximum security \"home\" for all of Gotham City's thugs, gangsters and insane criminal masterminds.\n\nSet inside the heavily fortified walls of a sprawling district in the heart of Gotham City, this highly anticipated sequel introduces a brand-new story that draws together a new all-star cast of classic characters and murderous villains from the Batman universe, as well as a vast range of new and enhanced gameplay features to deliver the ultimate experience as the Dark Knight."
                        },
                        new
                        {
                            GameID = 7331,
                            Name = "Uncharted 4: A Thief's End",
                            Rating = 90.962547055165686,
                            Summary = "Several years after his last adventure, retired fortune hunter, Nathan Drake, is forced back into the world of thieves. With the stakes much more personal, Drake embarks on a globe-trotting journey in pursuit of a historical conspiracy behind a fabled pirate treasure. His greatest adventure will test his physical limits, his resolve, and ultimately what he's willing to sacrifice to save the ones he loves."
                        },
                        new
                        {
                            GameID = 1164,
                            Name = "Tomb Raider",
                            Rating = 81.960577501446267,
                            Summary = "Tomb Raider explores the intense and gritty origin story of Lara Croft and her ascent from a young woman to a hardened survivor. Armed only with raw instincts and the ability to push beyond the limits of human endurance, Lara must fight to unravel the dark history of a forgotten island to escape its relentless hold."
                        },
                        new
                        {
                            GameID = 434,
                            Name = "Red Dead Redemption",
                            Rating = 89.340103940291641,
                            Summary = "A modern-day Western epic, Red Dead Redemption takes John Marston, a relic from the fast-closing time of the gunslinger, through an open-world filled with wildlife, mini games and shootouts. Marston sets out to hunt down his old gang mates for the government, who have taken away his family, and meets many characters emblematic of the Wild West, heroism and the new civilization along his journey."
                        },
                        new
                        {
                            GameID = 565,
                            Name = "Uncharted 2: Among Thieves",
                            Rating = 88.96713707224167,
                            Summary = "In the sequel to Drake's Fortune, Nathan Drake comes across a map that showcases the location of Marco Polo's missing ships. It takes him on a journey to find the infamous Cintamani Stone, and uncover the truth behind it."
                        },
                        new
                        {
                            GameID = 529,
                            Name = "Far Cry 3",
                            Rating = 83.732348718391108,
                            Summary = "Beyond the reach of civilization lies a lawless island ruled by violence. This is where you find yourself stranded, caught in a bloody conflict between the island’s psychotic warlords and indigenous rebels. Struggling to survive, your only hope of escape is through the muzzle of a gun. Discover the island’s dark secrets and take the fight to the enemy; improvise and use your environment to your advantage; and outwit its cast of ruthless, deranged inhabitants. Beware the beauty and mystery of this island of insanity… Where nothing is what is seems, you’ll need more than luck to escape alive."
                        },
                        new
                        {
                            GameID = 11156,
                            Name = "Horizon Zero Dawn",
                            Rating = 88.145144028010534,
                            Summary = "Welcome to a vibrant world rich with the beauty of nature – but inhabited by awe-inspiring, highly advanced machines. As a young machine hunter named Aloy, you must unravel the mysteries of this world and find your own destiny."
                        },
                        new
                        {
                            GameID = 16,
                            Name = "Fallout: New Vegas",
                            Rating = 87.019966534345784,
                            Summary = "In this first-person Western RPG, the player takes on the role of Courier 6, barely surviving after being robbed of their cargo, shot and put into a shallow grave by a New Vegas mob boss. The Courier sets out to track down their robbers and retrieve their cargo, and winds up getting tangled in the complex ideological and socioeconomic web of the many factions and settlements of post-nuclear Nevada."
                        },
                        new
                        {
                            GameID = 121,
                            Name = "Minecraft",
                            Rating = 84.033979625235503,
                            Summary = "Minecraft focuses on allowing the player to explore, interact with, and modify a dynamically-generated map made of one-cubic-meter-sized blocks. In addition to blocks, the environment features plants, mobs, and items. Some activities in the game include mining for ore, fighting hostile mobs, and crafting new blocks and tools by gathering various resources found in the game. The game's open-ended model allows players to create structures, creations, and artwork on various multiplayer servers or their single-player maps. Other features include redstone circuits for logic computations and remote actions, minecarts and tracks, and a mysterious underworld called the Nether. A designated but completely optional goal of the game is to travel to a dimension called the End, and defeat the ender dragon."
                        },
                        new
                        {
                            GameID = 1029,
                            Name = "The Legend of Zelda: Ocarina of Time",
                            Rating = 92.158555628900444,
                            Summary = "The Legend of Zelda: Ocarina of Time is the fifth main installment of The Legend of Zelda series and the first to be released for the Nintendo 64. It was one of the most highly anticipated games of its age, and is listed among the greatest video games ever created by numerous websites and magazines. The gameplay of Ocarina of Time was revolutionary for its time, it has arguably made more of an impact on later games in the series than any of its predecessors even though they had the same cores of exploration, dungeons, puzzles and item usage. Among the gameplay mechanics, one of the most noteworthy is the time-traveling system. The game begins with the player controlling the child Link, but later on an adult Link becomes a playable character as well and each of them has certain unique abilities. Ocarina of Time also introduces the use of music to solve puzzles: as new songs are learned, they can be used to solve puzzles, gain access to new areas and warp to different locations. Dungeon exploration is somewhat more puzzle-oriented than in earlier games but they are not too complex."
                        },
                        new
                        {
                            GameID = 75,
                            Name = "Mass Effect 3",
                            Rating = 85.17530971927863,
                            Summary = "Earth is burning. The Reapers have taken over and other civilizations are falling like dominoes. Lead the final fight to save humanity and take back Earth from these terrifying machines, Commander Shepard. You'll need backup for these battles. Fortunately, the galaxy has a habit of sending unexpected species your way. Recruit team members and forge new alliances, but be prepared to say goodbye at any time as partners make the ultimate sacrifice. It's time for Commander Shepard to fight for the fate of the human race and save the galaxy. No pressure, Commander.\n\nFight smarter. Take advantage of new powers and combat moves. Shepard can now blind fire at enemies and build tougher melee attacks. Plus, when you fight as a team you can combine new biotic and tech powers to unleash devastating Power Combos.\n\nBuild the final force. Build a team from a variety of races and classes and combine their skills to overcome impossible odds. You'll be joined by newcomers like James Vega, a tough-as-nails soldier, as well as EDI, a trusted AI in a newly acquired physical form. Keep an eye out for beloved characters from your past, but beware. Some may not survive the final battle...\n\nFace off against friends. Enjoy an integrated co-op multiplayer mode and team up with friends online to liberate key conflict zones from increasingly tough opponents. Customize your warrior and earn new weapons, armor, and abilities to build war preparedness stats in your single player campaign."
                        },
                        new
                        {
                            GameID = 1011,
                            Name = "Borderlands 2",
                            Rating = 84.33165391631124,
                            Summary = "A new era of shoot and loot is about to begin. Play as one of four new vault hunters facing off against a massive new world of creatures, psychos and the evil mastermind, Handsome Jack. Make new friends, arm them with a bazillion weapons and fight alongside them in 4 player co-op on a relentless quest for revenge and redemption across the undiscovered and unpredictable living planet."
                        },
                        new
                        {
                            GameID = 7351,
                            Name = "Doom",
                            Rating = 85.544041820657952,
                            Summary = "Developed by id software, the studio that pioneered the first-person shooter genre and created multiplayer Deathmatch, Doom returns as a brutally fun and challenging modern-day shooter experience. Relentless demons, impossibly destructive guns, and fast, fluid movement provide the foundation for intense, first-person combat – whether you’re obliterating demon hordes through the depths of Hell in the single-player campaign, or competing against your friends in numerous multiplayer modes. Expand your gameplay experience using Doom SnapMap game editor to easily create, play, and share your content with the world."
                        },
                        new
                        {
                            GameID = 7599,
                            Name = "Life is Strange",
                            Rating = 82.870118543267765,
                            Summary = "Life is Strange is a five part episodic game that sets out to revolutionize story based choice and consequence games by allowing the player to rewind time and affect the past, present and future."
                        },
                        new
                        {
                            GameID = 1074,
                            Name = "Super Mario 64",
                            Rating = 89.692847874733076,
                            Summary = "The first three dimensional entry in the Mario franchise, Super Mario 64 follows Mario as he puts his broadened 3D movement arsenal to use in order to rescue Princess Peach from the clutches of his arch rival Bowser. Mario has to jump into worlds-within-paintings ornamenting the walls of Peach's castle, uncover secrets and hidden challenges and collect golden stars as reward for platforming trials."
                        },
                        new
                        {
                            GameID = 623,
                            Name = "Call of Duty 4: Modern Warfare",
                            Rating = 84.413485983002815,
                            Summary = "Call of Duty 4: Modern Warfare differs from previous installments of the Call of Duty series. Previous Call of Duty games have a distinct three country-specific campaign style, while Call of Duty 4 has a more film-like plot with interlaced story lines from the perspectives of Sgt. Paul Jackson of the Marines 1st Force Recon and Sgt. 'Soap' MacTavish of the British 22nd SAS Regiment."
                        },
                        new
                        {
                            GameID = 1070,
                            Name = "Super Mario World",
                            Rating = 92.607371113631487,
                            Summary = "A 2D platformer and first entry on the SNES in the Super Mario franchise, Super Mario World follows Mario as he attempts to defeat Bowser's underlings and rescue Princess Peach from his clutches. The game features a save system, a less linear world map, an expanded movement arsenal and numerous new items for Mario, alongside new approaches to level design and art direction."
                        },
                        new
                        {
                            GameID = 128,
                            Name = "Assassin's Creed",
                            Rating = 73.271366521090584,
                            Summary = "Assassin's Creed is a non-linear action-adventure video game, during which the player controls a 12th-century Levantine Assassin named Altaïr Ibn-La'Ahad during the Third Crusade, whose life is experienced through the Animus by his 21st century descendant, Desmond Miles."
                        },
                        new
                        {
                            GameID = 533,
                            Name = "Dishonored",
                            Rating = 84.874780945462049,
                            Summary = "Dishonored is an immersive first-person action game that casts you as a supernatural assassin driven by revenge. With Dishonored’s flexible combat system, creatively eliminate your targets as you combine the supernatural abilities, weapons and unusual gadgets at your disposal. Pursue your enemies under the cover of darkness or ruthlessly attack them head on with weapons drawn. The outcome of each mission plays out based on the choices you make."
                        },
                        new
                        {
                            GameID = 731,
                            Name = "Grand Theft Auto IV",
                            Rating = 83.571344737558988,
                            Summary = "Grand Theft Auto IV is an action-adventure video game developed by Rockstar North and published by Rockstar Games. It is the eleventh title in the Grand Theft Auto series, and the first main entry since 2004's Grand Theft Auto: San Andreas.\n\nThe game is played from a third-person perspective and its world is navigated on-foot or by vehicle. Throughout the single-player mode, players play as Niko Bellic. An online multiplayer mode is included with the game, allowing up to 32 players to engage in both co-operative and competitive gameplay in a recreation of the single-player setting.\n\nTwo expansion packs were later released for the game, The Lost and Damned and The Ballad of Gay Tony, which both feature new plots that are interconnected with the main Grand Theft Auto IV storyline, and follow new protagonists."
                        },
                        new
                        {
                            GameID = 18,
                            Name = "Max Payne",
                            Rating = 85.965926921874683,
                            Summary = "Max Payne is a man with nothing to lose in the violent, cold urban night. A fugitive undercover cop framed for murder, hunted by cops and the mob, Max is a man with his back against the wall, fighting a battle he cannot hope to win. Max Payne is a relentless story-driven game about a man on the edge, fighting to clear his name while struggling to uncover the truth about his slain family amongst a myriad of plot-twists and twisted thugs in the gritty bowels of New York during the century's worst blizzard.\n\nThe groundbreaking original cinematic action-shooter, Max Payne introduced the concept of Bullet Time in videogames. Through its stylish slow-motion gunplay combined with a dark and twisted story, Max Payne redefined the action-shooter genre."
                        },
                        new
                        {
                            GameID = 1871,
                            Name = "The Walking Dead",
                            Rating = 85.667994505549899,
                            Summary = "The Walking Dead: Season One (also known as The Walking Dead: The Game) is an episodic interactive drama graphic adventure video game developed and published by Telltale Games. Based on Robert Kirkman's The Walking Dead comic book series, the game consists of five episodes, released between April and November 2012. It is available for Android, iOS, Kindle Fire HDX, Microsoft Windows, Mac OS X, PlayStation 3, PlayStation Vita, Xbox 360, PlayStation 4 and Xbox One. The game is the first of The Walking Dead video game series published by Telltale."
                        },
                        new
                        {
                            GameID = 113,
                            Name = "Assassin's Creed Brotherhood",
                            Rating = 82.853936686042431,
                            Summary = "Live and breathe as Ezio, a legendary Master Assassin, in his enduring struggle against the powerful Templar Order. He must journey into Italy’s greatest city, Rome, center of power, greed and corruption to strike at the heart of the enemy.\nDefeating the corrupt tyrants entrenched there will require not only strength, but leadership, as Ezio commands an entire Brotherhood who will rally to his side. Only by working together can the Assassins defeat their mortal enemies.\nAnd for the first time, introducing a never-before-seen multiplayer layer that allows you to choose from a wide range of unique characters, each with their own signature weapons and assassination techniques, and match your skills against other players from around the world.\nIt’s time to join the Brotherhood."
                        },
                        new
                        {
                            GameID = 15,
                            Name = "Fallout 3",
                            Rating = 83.527103920909681,
                            Summary = "Fallout 3 from the creators of the award-winning Oblivion, featuring one of the most realized game worlds ever created. Create any kind of character you want and explore the open wastes of post-apocalyptic Washington D.C. Every minute is a fight for survival as you encounter Super Mutants, Ghouls, Raiders and other dangers of the Wasteland. Prepare for the future.\n\nThe third game in the Fallout series, Fallout 3 is a singleplayer action role-playing game (RPG) set in a post-apocalyptic Washington DC. Combining the horrific insanity of the Cold War era theory of mutually assured destruction gone terribly wrong, with the kitschy naivety of American 1950s nuclear propaganda, Fallout 3 will satisfy both players familiar with the popular first two games in its series as well as those coming to the franchise for the first time."
                        },
                        new
                        {
                            GameID = 1970,
                            Name = "Assassin's Creed IV Black Flag",
                            Rating = 82.938127887579839,
                            Summary = "Assassin’s Creed IV Black Flag begins in 1715, when pirates established a lawless republic in the Caribbean and ruled the land and seas. These outlaws paralyzed navies, halted international trade, and plundered vast fortunes. They threatened the power structures that ruled Europe, inspired the imaginations of millions, and left a legacy that still endures."
                        },
                        new
                        {
                            GameID = 12517,
                            Name = "Undertale",
                            Rating = 86.571986902300068,
                            Summary = "A small child falls into the Underground, where monsters have long been banished by humans and are hunting every human that they find. The player controls the child as they try to make it back to the Surface through hostile environments, all the while engaging with a turn-based combat system with puzzle-solving and bullet hell elements, as well as other unconventional game mechanics."
                        },
                        new
                        {
                            GameID = 76,
                            Name = "Dragon Age: Origins",
                            Rating = 86.44866918060977,
                            Summary = "Dragon Age: Origins is a third-person role-playing game described as a spiritual successor to Baldur's Gate and Neverwinter Nights franchises. Players create their own character by customizing gender and appearance as well as choosing a race and class. Combat is in real time with the ability to pause at any moment: tactical options include an editor which allows the player to give the AI detailed instructions on how to behave in every possible situation. Although the main storyline is the same for every character created, the game features six unique prologues, two for each race. Dragon Age: Origins received critical acclaim upon release, with praise mostly directed at its story, setting, characters, music and combat system."
                        },
                        new
                        {
                            GameID = 19565,
                            Name = "Marvel's Spider-Man",
                            Rating = 87.171760660369827,
                            Summary = "Starring the world’s most iconic Super Hero, Spider-Man features the acrobatic abilities, improvisation and web-slinging that the wall-crawler is famous for, while also introducing elements never-before-seen in a Spider-Man game. From traversing with parkour and utilizing the environment, to new combat and blockbuster set pieces, it’s Spider-Man unlike any you’ve played before."
                        },
                        new
                        {
                            GameID = 9630,
                            Name = "Fallout 4",
                            Rating = 79.984937502201859,
                            Summary = "Bethesda Game Studios welcome you to the world of Fallout 4, their most ambitious game ever, and the next generation of open-world gaming. As the sole survivor of Vault 111, you enter a world destroyed by nuclear war. Every second is a fight for survival, and every choice is yours. Only you can rebuild and determine the fate of the Wasteland. Welcome home."
                        },
                        new
                        {
                            GameID = 26758,
                            Name = "Super Mario Odyssey",
                            Rating = 89.574919840990475,
                            Summary = "Explore incredible places far from the Mushroom Kingdom as you join Mario and his new ally Cappy on a massive, globe-trotting 3D adventure. Use amazing new abilities, like the power to capture and control objects, animals, and enemies to collect Power Moons so you can power up the Odyssey airship and save Princess Peach from Bowser’s wedding plans!"
                        },
                        new
                        {
                            GameID = 7342,
                            Name = "Inside",
                            Rating = 86.113629232474921,
                            Summary = "An atmospheric 2D side-scroller in which, hunted and alone, a boy finds himself drawn into the center of a dark project and struggles to preserve his identity."
                        });
                });

            modelBuilder.Entity("questvault.Models.GamesGenres", b =>
                {
                    b.Property<int>("GamesID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("GenresID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("GamesID", "GenresID");

                    b.HasIndex("GenresID");

                    b.ToTable("GamesGenres");

                    b.HasData(
                        new
                        {
                            GamesID = 1020,
                            GenresID = 5
                        },
                        new
                        {
                            GamesID = 1020,
                            GenresID = 10
                        },
                        new
                        {
                            GamesID = 1020,
                            GenresID = 31
                        },
                        new
                        {
                            GamesID = 1942,
                            GenresID = 12
                        },
                        new
                        {
                            GamesID = 1942,
                            GenresID = 31
                        },
                        new
                        {
                            GamesID = 72,
                            GenresID = 5
                        },
                        new
                        {
                            GamesID = 72,
                            GenresID = 8
                        },
                        new
                        {
                            GamesID = 72,
                            GenresID = 9
                        },
                        new
                        {
                            GamesID = 72,
                            GenresID = 31
                        },
                        new
                        {
                            GamesID = 472,
                            GenresID = 12
                        },
                        new
                        {
                            GamesID = 472,
                            GenresID = 31
                        },
                        new
                        {
                            GamesID = 71,
                            GenresID = 5
                        },
                        new
                        {
                            GamesID = 71,
                            GenresID = 8
                        },
                        new
                        {
                            GamesID = 71,
                            GenresID = 9
                        },
                        new
                        {
                            GamesID = 732,
                            GenresID = 5
                        },
                        new
                        {
                            GamesID = 732,
                            GenresID = 10
                        },
                        new
                        {
                            GamesID = 732,
                            GenresID = 31
                        },
                        new
                        {
                            GamesID = 233,
                            GenresID = 5
                        },
                        new
                        {
                            GamesID = 1009,
                            GenresID = 5
                        },
                        new
                        {
                            GamesID = 1009,
                            GenresID = 31
                        },
                        new
                        {
                            GamesID = 20,
                            GenresID = 5
                        },
                        new
                        {
                            GamesID = 20,
                            GenresID = 9
                        },
                        new
                        {
                            GamesID = 20,
                            GenresID = 12
                        },
                        new
                        {
                            GamesID = 20,
                            GenresID = 31
                        },
                        new
                        {
                            GamesID = 127,
                            GenresID = 8
                        },
                        new
                        {
                            GamesID = 127,
                            GenresID = 31
                        },
                        new
                        {
                            GamesID = 733,
                            GenresID = 5
                        },
                        new
                        {
                            GamesID = 733,
                            GenresID = 10
                        },
                        new
                        {
                            GamesID = 733,
                            GenresID = 31
                        },
                        new
                        {
                            GamesID = 733,
                            GenresID = 33
                        },
                        new
                        {
                            GamesID = 19560,
                            GenresID = 12
                        },
                        new
                        {
                            GamesID = 19560,
                            GenresID = 25
                        },
                        new
                        {
                            GamesID = 19560,
                            GenresID = 31
                        },
                        new
                        {
                            GamesID = 538,
                            GenresID = 5
                        },
                        new
                        {
                            GamesID = 538,
                            GenresID = 31
                        },
                        new
                        {
                            GamesID = 74,
                            GenresID = 5
                        },
                        new
                        {
                            GamesID = 74,
                            GenresID = 12
                        },
                        new
                        {
                            GamesID = 74,
                            GenresID = 31
                        },
                        new
                        {
                            GamesID = 231,
                            GenresID = 5
                        },
                        new
                        {
                            GamesID = 231,
                            GenresID = 9
                        },
                        new
                        {
                            GamesID = 231,
                            GenresID = 31
                        },
                        new
                        {
                            GamesID = 500,
                            GenresID = 25
                        },
                        new
                        {
                            GamesID = 500,
                            GenresID = 31
                        },
                        new
                        {
                            GamesID = 7346,
                            GenresID = 9
                        },
                        new
                        {
                            GamesID = 7346,
                            GenresID = 12
                        },
                        new
                        {
                            GamesID = 7346,
                            GenresID = 31
                        },
                        new
                        {
                            GamesID = 25076,
                            GenresID = 5
                        },
                        new
                        {
                            GamesID = 25076,
                            GenresID = 12
                        },
                        new
                        {
                            GamesID = 25076,
                            GenresID = 31
                        },
                        new
                        {
                            GamesID = 73,
                            GenresID = 5
                        },
                        new
                        {
                            GamesID = 73,
                            GenresID = 12
                        },
                        new
                        {
                            GamesID = 501,
                            GenresID = 25
                        },
                        new
                        {
                            GamesID = 501,
                            GenresID = 31
                        },
                        new
                        {
                            GamesID = 7331,
                            GenresID = 5
                        },
                        new
                        {
                            GamesID = 7331,
                            GenresID = 31
                        },
                        new
                        {
                            GamesID = 1164,
                            GenresID = 5
                        },
                        new
                        {
                            GamesID = 1164,
                            GenresID = 8
                        },
                        new
                        {
                            GamesID = 1164,
                            GenresID = 9
                        },
                        new
                        {
                            GamesID = 1164,
                            GenresID = 31
                        },
                        new
                        {
                            GamesID = 434,
                            GenresID = 5
                        },
                        new
                        {
                            GamesID = 434,
                            GenresID = 12
                        },
                        new
                        {
                            GamesID = 434,
                            GenresID = 31
                        },
                        new
                        {
                            GamesID = 565,
                            GenresID = 5
                        },
                        new
                        {
                            GamesID = 565,
                            GenresID = 8
                        },
                        new
                        {
                            GamesID = 565,
                            GenresID = 31
                        },
                        new
                        {
                            GamesID = 529,
                            GenresID = 5
                        },
                        new
                        {
                            GamesID = 529,
                            GenresID = 31
                        },
                        new
                        {
                            GamesID = 11156,
                            GenresID = 5
                        },
                        new
                        {
                            GamesID = 11156,
                            GenresID = 12
                        },
                        new
                        {
                            GamesID = 11156,
                            GenresID = 31
                        },
                        new
                        {
                            GamesID = 16,
                            GenresID = 5
                        },
                        new
                        {
                            GamesID = 16,
                            GenresID = 12
                        },
                        new
                        {
                            GamesID = 121,
                            GenresID = 13
                        },
                        new
                        {
                            GamesID = 121,
                            GenresID = 31
                        },
                        new
                        {
                            GamesID = 1029,
                            GenresID = 12
                        },
                        new
                        {
                            GamesID = 1029,
                            GenresID = 31
                        },
                        new
                        {
                            GamesID = 75,
                            GenresID = 5
                        },
                        new
                        {
                            GamesID = 75,
                            GenresID = 12
                        },
                        new
                        {
                            GamesID = 75,
                            GenresID = 31
                        },
                        new
                        {
                            GamesID = 1011,
                            GenresID = 5
                        },
                        new
                        {
                            GamesID = 1011,
                            GenresID = 12
                        },
                        new
                        {
                            GamesID = 7351,
                            GenresID = 5
                        },
                        new
                        {
                            GamesID = 7351,
                            GenresID = 9
                        },
                        new
                        {
                            GamesID = 7599,
                            GenresID = 9
                        },
                        new
                        {
                            GamesID = 7599,
                            GenresID = 12
                        },
                        new
                        {
                            GamesID = 7599,
                            GenresID = 31
                        },
                        new
                        {
                            GamesID = 7599,
                            GenresID = 32
                        },
                        new
                        {
                            GamesID = 1074,
                            GenresID = 8
                        },
                        new
                        {
                            GamesID = 1074,
                            GenresID = 31
                        },
                        new
                        {
                            GamesID = 623,
                            GenresID = 5
                        },
                        new
                        {
                            GamesID = 623,
                            GenresID = 13
                        },
                        new
                        {
                            GamesID = 1070,
                            GenresID = 8
                        },
                        new
                        {
                            GamesID = 1070,
                            GenresID = 31
                        },
                        new
                        {
                            GamesID = 128,
                            GenresID = 8
                        },
                        new
                        {
                            GamesID = 128,
                            GenresID = 31
                        },
                        new
                        {
                            GamesID = 533,
                            GenresID = 9
                        },
                        new
                        {
                            GamesID = 533,
                            GenresID = 12
                        },
                        new
                        {
                            GamesID = 533,
                            GenresID = 31
                        },
                        new
                        {
                            GamesID = 731,
                            GenresID = 5
                        },
                        new
                        {
                            GamesID = 731,
                            GenresID = 10
                        },
                        new
                        {
                            GamesID = 731,
                            GenresID = 31
                        },
                        new
                        {
                            GamesID = 18,
                            GenresID = 5
                        },
                        new
                        {
                            GamesID = 1871,
                            GenresID = 2
                        },
                        new
                        {
                            GamesID = 1871,
                            GenresID = 31
                        },
                        new
                        {
                            GamesID = 113,
                            GenresID = 9
                        },
                        new
                        {
                            GamesID = 113,
                            GenresID = 31
                        },
                        new
                        {
                            GamesID = 15,
                            GenresID = 5
                        },
                        new
                        {
                            GamesID = 15,
                            GenresID = 12
                        },
                        new
                        {
                            GamesID = 1970,
                            GenresID = 8
                        },
                        new
                        {
                            GamesID = 1970,
                            GenresID = 31
                        },
                        new
                        {
                            GamesID = 12517,
                            GenresID = 12
                        },
                        new
                        {
                            GamesID = 12517,
                            GenresID = 16
                        },
                        new
                        {
                            GamesID = 12517,
                            GenresID = 31
                        },
                        new
                        {
                            GamesID = 12517,
                            GenresID = 32
                        },
                        new
                        {
                            GamesID = 76,
                            GenresID = 12
                        },
                        new
                        {
                            GamesID = 19565,
                            GenresID = 25
                        },
                        new
                        {
                            GamesID = 19565,
                            GenresID = 31
                        },
                        new
                        {
                            GamesID = 9630,
                            GenresID = 5
                        },
                        new
                        {
                            GamesID = 9630,
                            GenresID = 12
                        },
                        new
                        {
                            GamesID = 26758,
                            GenresID = 8
                        },
                        new
                        {
                            GamesID = 26758,
                            GenresID = 31
                        },
                        new
                        {
                            GamesID = 7342,
                            GenresID = 8
                        },
                        new
                        {
                            GamesID = 7342,
                            GenresID = 9
                        },
                        new
                        {
                            GamesID = 7342,
                            GenresID = 31
                        },
                        new
                        {
                            GamesID = 7342,
                            GenresID = 32
                        });
                });

            modelBuilder.Entity("questvault.Models.Genres", b =>
                {
                    b.Property<int>("GenreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenreID"));

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreID");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreID = 2,
                            GenreName = "Point-and-click"
                        },
                        new
                        {
                            GenreID = 4,
                            GenreName = "Fighting"
                        },
                        new
                        {
                            GenreID = 5,
                            GenreName = "Shooter"
                        },
                        new
                        {
                            GenreID = 7,
                            GenreName = "Music"
                        },
                        new
                        {
                            GenreID = 8,
                            GenreName = "Platform"
                        },
                        new
                        {
                            GenreID = 9,
                            GenreName = "Puzzle"
                        },
                        new
                        {
                            GenreID = 10,
                            GenreName = "Racing"
                        },
                        new
                        {
                            GenreID = 11,
                            GenreName = "Real Time Strategy (RTS)"
                        },
                        new
                        {
                            GenreID = 12,
                            GenreName = "Role-playing (RPG)"
                        },
                        new
                        {
                            GenreID = 13,
                            GenreName = "Simulator"
                        },
                        new
                        {
                            GenreID = 14,
                            GenreName = "Sport"
                        },
                        new
                        {
                            GenreID = 15,
                            GenreName = "Strategy"
                        },
                        new
                        {
                            GenreID = 16,
                            GenreName = "Turn-based strategy (TBS)"
                        },
                        new
                        {
                            GenreID = 24,
                            GenreName = "Tactical"
                        },
                        new
                        {
                            GenreID = 25,
                            GenreName = "Hack and slash/Beat 'em up"
                        },
                        new
                        {
                            GenreID = 26,
                            GenreName = "Quiz/Trivia"
                        },
                        new
                        {
                            GenreID = 30,
                            GenreName = "Pinball"
                        },
                        new
                        {
                            GenreID = 31,
                            GenreName = "Adventure"
                        },
                        new
                        {
                            GenreID = 32,
                            GenreName = "Indie"
                        },
                        new
                        {
                            GenreID = 33,
                            GenreName = "Arcade"
                        },
                        new
                        {
                            GenreID = 34,
                            GenreName = "Visual Novel"
                        },
                        new
                        {
                            GenreID = 35,
                            GenreName = "Card & Board Game"
                        },
                        new
                        {
                            GenreID = 36,
                            GenreName = "MOBA"
                        });
                });

            modelBuilder.Entity("questvault.Models.Platform", b =>
                {
                    b.Property<int>("PlatformID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlatformID"));

                    b.Property<string>("PlatformName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlatformID");

                    b.ToTable("Platform");
                });

            modelBuilder.Entity("questvault.Models.TwoFactorAuthenticationTokens", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(0);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId1")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("EmailTokens");
                });

            modelBuilder.Entity("questvault.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("Clearance")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeactivated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("questvault.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("questvault.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("questvault.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("questvault.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("questvault.Models.Games", b =>
                {
                    b.HasOne("questvault.Models.Company", null)
                        .WithMany("Games")
                        .HasForeignKey("CompanyID");

                    b.HasOne("questvault.Models.Platform", null)
                        .WithMany("Games")
                        .HasForeignKey("PlatformID");
                });

            modelBuilder.Entity("questvault.Models.GamesGenres", b =>
                {
                    b.HasOne("questvault.Models.Games", "Game")
                        .WithMany("GamesGenres")
                        .HasForeignKey("GamesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("questvault.Models.Genres", "Genre")
                        .WithMany("GamesGenres")
                        .HasForeignKey("GenresID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("questvault.Models.TwoFactorAuthenticationTokens", b =>
                {
                    b.HasOne("questvault.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("questvault.Models.Company", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("questvault.Models.Games", b =>
                {
                    b.Navigation("GamesGenres");
                });

            modelBuilder.Entity("questvault.Models.Genres", b =>
                {
                    b.Navigation("GamesGenres");
                });

            modelBuilder.Entity("questvault.Models.Platform", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
