<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h6_Administrator</name>
   <tag></tag>
   <elementGuidId>f1380a28-9d3b-4433-a448-164a86f29dcf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h6.profile-username</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-body']/main/section/div/div[2]/div[2]/h6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h6</value>
      <webElementGuid>933ccb3f-07df-4738-a8ca-3fcdfc0d4504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>profile-username</value>
      <webElementGuid>a837e5a0-0b01-4978-8651-4c94311484b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Administrator</value>
      <webElementGuid>1f3c22b9-08a3-47d5-8dea-21fedb024657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-body&quot;)/main[@class=&quot;pb-3&quot;]/section[@class=&quot;profile-banner d-flex align-items-center&quot;]/div[@class=&quot;container-fluid d-flex align-items-center justify-content-center mt-3&quot;]/div[@class=&quot;d-flex row ms-3 align-items-center col-7&quot;]/div[@class=&quot;row container-fluid&quot;]/h6[@class=&quot;profile-username&quot;]</value>
      <webElementGuid>b34d265f-d7db-49a9-8b83-7e028a3fa7a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-body']/main/section/div/div[2]/div[2]/h6</value>
      <webElementGuid>19a773bf-d6a1-401c-9413-3181c2ff7e1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tBatista'])[2]/following::h6[1]</value>
      <webElementGuid>9e05fb43-2b2d-42e7-b27a-fd135c9a663a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Top 5'])[1]/preceding::h6[7]</value>
      <webElementGuid>8189f3aa-8228-4b32-8a43-64a26511bd00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright @ 2023-2024, QuestVault. All Rights Reserved.'])[1]/preceding::h6[7]</value>
      <webElementGuid>6f94deb5-24c6-4a66-9d19-4e8430f1d3fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Administrator']/parent::*</value>
      <webElementGuid>b493c5b5-3b8f-47dd-8c69-8596227154a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h6</value>
      <webElementGuid>2f3be5f4-86ad-4905-af81-756044511be5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h6[(text() = 'Administrator' or . = 'Administrator')]</value>
      <webElementGuid>cfd41e41-2570-431b-b3d4-ed005ad2b870</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
