<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h6_Administrator</name>
   <tag></tag>
   <elementGuidId>f1380a28-9d3b-4433-a448-164a86f29dcf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h6.profile-role</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-body']/main/section/div/div[2]/div/div/h6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h6</value>
      <webElementGuid>7c29058e-1336-4fae-aaf9-ea3d4e955320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>profile-role</value>
      <webElementGuid>8443a8bb-b2f4-44d5-a4cd-7a2edc13af86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Administrator</value>
      <webElementGuid>2322ed4a-adcd-4dc5-84b1-bcb3523d597e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-body&quot;)/main[@class=&quot;pb-3&quot;]/section[@class=&quot;profile-banner d-flex align-items-center&quot;]/div[@class=&quot;container-fluid d-flex align-items-center justify-content-center mt-3&quot;]/div[@class=&quot;d-flex row ms-3 align-items-center col-7&quot;]/div[@class=&quot;profile-details d-inline-flex mb-4&quot;]/div[@class=&quot;col-auto&quot;]/h6[@class=&quot;profile-role&quot;]</value>
      <webElementGuid>629cd9d0-ece8-481c-a47c-84886936cec0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-body']/main/section/div/div[2]/div/div/h6</value>
      <webElementGuid>8561aefb-6919-4eeb-8f74-c55d3f0ef3c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tBatista'])[2]/following::h6[1]</value>
      <webElementGuid>a0bbb12f-61f8-41f3-bffb-a9910fced976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::h6[1]</value>
      <webElementGuid>3b06b274-fe45-4d37-b81b-33bc99698e39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Top 5'])[1]/preceding::h6[7]</value>
      <webElementGuid>7709b289-bdf1-478f-9de0-25f5771c0ae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Administrator']/parent::*</value>
      <webElementGuid>b6b914ba-a5a1-4fa5-9dd3-ade1e18115e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h6</value>
      <webElementGuid>2e8dbe9c-f8fb-44f0-a49b-b247c15ad278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h6[(text() = 'Administrator' or . = 'Administrator')]</value>
      <webElementGuid>59915dd6-9a51-4027-8a10-a89ade0a44e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
