<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Library_img-size-sm</name>
   <tag></tag>
   <elementGuidId>7c889d02-b6c6-4235-86bf-d9c4bccdf487</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.img-size-sm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-body']/main/section/div/div[2]/div[3]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5fecb50c-93d0-4ab3-a43e-da900208d3e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-size-sm</value>
      <webElementGuid>7b961c6a-7e55-4037-9242-3ddce6271db0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/img/external/Steam_Logo.png</value>
      <webElementGuid>36729ec2-d1cd-473e-8164-4397a9ac8aee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Steam Logo</value>
      <webElementGuid>1c6e3326-88f1-49a5-9168-258c716c63fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-body&quot;)/main[@class=&quot;pb-3&quot;]/section[@class=&quot;profile-banner d-flex align-items-center&quot;]/div[@class=&quot;container-fluid d-flex align-items-center justify-content-center mt-3&quot;]/div[@class=&quot;d-flex row ms-3 align-items-center col-7&quot;]/div[@class=&quot;profile-connects row container-fluid&quot;]/a[1]/img[@class=&quot;img-size-sm&quot;]</value>
      <webElementGuid>e8883530-d908-4792-9a51-fc4d6f4c998e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-body']/main/section/div/div[2]/div[3]/a/img</value>
      <webElementGuid>390628f5-b34c-41a9-8f01-f0c843f2299a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Steam Logo']</value>
      <webElementGuid>1bfb0a22-fb4a-40e7-8d8f-7cf422dc385e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/img</value>
      <webElementGuid>71042d8a-f7ad-47bd-824e-a0bc80d8cc21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/img/external/Steam_Logo.png' and @alt = 'Steam Logo']</value>
      <webElementGuid>219ab8ce-769f-4f26-b0da-1d72cb998244</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
