<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Teste_icon-trash</name>
   <tag></tag>
   <elementGuidId>294cc16e-755a-4e15-951a-c103ae689085</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#icon-trash</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='icon-trash']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Trash Can Icon&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6a6b0a41-9311-4913-9a49-9ff0ace7a6b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>icon-trash</value>
      <webElementGuid>70de99bc-2b19-442d-bc91-12eaad07afdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-vector</value>
      <webElementGuid>3df60609-d14a-46bc-9995-6b13153692bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/img/vector/trash-can-solid.svg</value>
      <webElementGuid>e5b73aa0-92e5-4b99-aa6a-21e305ce9bcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Trash Can Icon</value>
      <webElementGuid>504167e2-3140-45aa-a3b6-22cc1ee961ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;icon-trash&quot;)</value>
      <webElementGuid>ca1c0d73-7af8-41b4-b2a4-5e92a97c9af1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='icon-trash']</value>
      <webElementGuid>54a78788-fea1-4e4c-9677-05e9ccd0822d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Trash Can Icon']</value>
      <webElementGuid>5608aa48-8cc1-4f34-952b-30def93ed670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a/img</value>
      <webElementGuid>fa1d39a5-8d08-47cc-9cfa-92ccdf44801e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'icon-trash' and @src = '/img/vector/trash-can-solid.svg' and @alt = 'Trash Can Icon']</value>
      <webElementGuid>ef4846ef-c8cb-42bf-a2de-71631814c863</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
