<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Teste_icon-trash</name>
   <tag></tag>
   <elementGuidId>294cc16e-755a-4e15-951a-c103ae689085</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'icon-trash' and @src = '/img/vector/trash-can-solid.svg' and @alt = 'Trash Can Icon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#icon-trash</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='icon-trash']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Trash Can Icon&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>710a30ef-1fdd-4dc3-91b4-f518aefbe024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>icon-trash</value>
      <webElementGuid>9185acf9-493b-44d2-a8f9-4e6fb44ce3cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-vector</value>
      <webElementGuid>5665f457-e0d2-4665-822c-df2093935269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/img/vector/trash-can-solid.svg</value>
      <webElementGuid>20fa9f23-ac60-4eb1-86c2-64fa3ea4ed8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Trash Can Icon</value>
      <webElementGuid>f52a0486-f4f0-4cbf-801c-b410548f0d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;icon-trash&quot;)</value>
      <webElementGuid>9d31a095-31d2-480f-ae22-409b97468ca4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='icon-trash']</value>
      <webElementGuid>d1e30a42-7992-4a97-b8b8-d829b5cec279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Trash Can Icon']</value>
      <webElementGuid>e1f3b511-7d87-4ee9-b6f5-6108db741003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a/img</value>
      <webElementGuid>94f2a723-7890-4beb-93b6-dfef246c42f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'icon-trash' and @src = '/img/vector/trash-can-solid.svg' and @alt = 'Trash Can Icon']</value>
      <webElementGuid>1cca1556-2942-4266-8404-72a19df17fe8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
