<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Teste_icon-deny</name>
   <tag></tag>
   <elementGuidId>3a2eac15-6457-4eb5-8a63-7e8be0eb190b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#icon-deny</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='icon-deny']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Deny Icon&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f1542316-ff01-4405-b18e-24fc7ae70699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>icon-deny</value>
      <webElementGuid>100a615e-0e34-400b-af9f-eb35e0170cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-vector</value>
      <webElementGuid>befd96b2-013d-4458-8033-86100b9ac28c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/img/vector/circle-xmark-solid.svg</value>
      <webElementGuid>997405b4-e62b-49e3-a4e6-9368b9028dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Deny Icon</value>
      <webElementGuid>5cfdd85c-cd63-4a78-908e-25a72bc47222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;icon-deny&quot;)</value>
      <webElementGuid>34b67b17-efe2-4e7f-b3b0-1f86fbf215ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='icon-deny']</value>
      <webElementGuid>2a8791e0-6669-47d7-8ffc-be251ec5d70b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Deny Icon']</value>
      <webElementGuid>e792df57-2547-48aa-bba2-bf3e8e62e03e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a[2]/img</value>
      <webElementGuid>cecdc6e8-5349-4f7b-99cb-d94fd2972fa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'icon-deny' and @src = '/img/vector/circle-xmark-solid.svg' and @alt = 'Deny Icon']</value>
      <webElementGuid>69fd562b-c363-4dcc-b817-6a005741973c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
