<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Teste_icon-accept</name>
   <tag></tag>
   <elementGuidId>2a2f3dd9-c269-4b2e-807d-df14ba15fa0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#icon-accept</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='icon-accept']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Confirm Icon&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>876ce9d2-f40a-4a98-a59d-343d3a348ca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>icon-accept</value>
      <webElementGuid>a74963f4-d392-462c-85f8-d211bf0df5a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-vector</value>
      <webElementGuid>763a3878-33e1-4070-a367-0df1502491f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/img/vector/circle-check-solid.svg</value>
      <webElementGuid>e0c70447-7ebd-4c94-85cc-2ec4a01f33f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Confirm Icon</value>
      <webElementGuid>6f0f1eb6-d6a9-477a-96cb-97ac5f8a4444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;icon-accept&quot;)</value>
      <webElementGuid>54308a8b-4f54-41ce-9e25-6349759318f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='icon-accept']</value>
      <webElementGuid>7fb845de-54c7-43fe-b416-7f2440252660</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Confirm Icon']</value>
      <webElementGuid>ab18ffc4-a446-4023-8d08-ec527a9aa6dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a/img</value>
      <webElementGuid>e1fbd4c5-a15c-41f4-a610-edd5bbff5a11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'icon-accept' and @src = '/img/vector/circle-check-solid.svg' and @alt = 'Confirm Icon']</value>
      <webElementGuid>cd3cd817-8905-4904-b5a3-27cb97900040</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
