<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Teste_icon-accept</name>
   <tag></tag>
   <elementGuidId>2a2f3dd9-c269-4b2e-807d-df14ba15fa0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'icon-accept' and @src = '/img/vector/circle-check-solid.svg' and @alt = 'Confirm Icon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#icon-accept</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='icon-accept']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Confirm Icon&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c120df93-c18f-4d77-a00c-10a3e70c67f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>icon-accept</value>
      <webElementGuid>1cc6aad6-1323-4c64-9edd-e6c8af58b2c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-vector</value>
      <webElementGuid>fd8786bd-a021-4643-bcfe-2e8d73db6e12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/img/vector/circle-check-solid.svg</value>
      <webElementGuid>c3ef0624-e422-4976-b680-807f7640dd92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Confirm Icon</value>
      <webElementGuid>bf13f6fe-acb2-4953-ac78-a1f612f45ec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;icon-accept&quot;)</value>
      <webElementGuid>66440d6c-63a8-4694-9feb-026fbc6e4cdc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='icon-accept']</value>
      <webElementGuid>8e80229b-5a4b-48ee-939a-13ae0ef1d0fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Confirm Icon']</value>
      <webElementGuid>d18d1c23-e0d5-4c31-a225-d57dee7bc770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a/img</value>
      <webElementGuid>8993dd9c-6b24-4c24-9512-963a6cbd1fc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'icon-accept' and @src = '/img/vector/circle-check-solid.svg' and @alt = 'Confirm Icon']</value>
      <webElementGuid>2e666b67-9529-4a43-9b41-7b1a66a2aac1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
