<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_notAdmin</name>
   <tag></tag>
   <elementGuidId>0a7d7afa-4bc5-45c2-ab38-a33666455b5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-body']/main/div/div[2]/table/tbody/tr/td[5]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1fbe2444-6d8a-4ecc-92da-1838088b6473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>notAdmin</value>
      <webElementGuid>01f8e320-8fbf-42e0-950f-799d266c597e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-body&quot;)/main[@class=&quot;pb-3&quot;]/div[@class=&quot;friends-page&quot;]/div[@class=&quot;container mt-5&quot;]/table[@class=&quot;table d-flex table-dark table-sm table-profile&quot;]/tbody[@class=&quot;container d-inline-flex&quot;]/tr[@class=&quot;row d-flex justify-content-between align-items-center&quot;]/td[@class=&quot;d-flex mt-5 me-4 align-items-center justify-content-center&quot;]/a[1]/span[1]</value>
      <webElementGuid>90ea377c-758f-4a2a-ba4f-fbc1615f0181</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-body']/main/div/div[2]/table/tbody/tr/td[5]/a/span</value>
      <webElementGuid>37cbb548-e65d-425c-afaa-dd1fd6e86675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LispEnjoyer'])[1]/following::span[1]</value>
      <webElementGuid>bb62a6fc-0036-43d8-baa6-384eee861562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='coelho'])[1]/following::span[2]</value>
      <webElementGuid>fca12fee-aeda-46e8-8dbf-baf327fa990e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright @ 2023-2024, QuestVault. All Rights Reserved.'])[1]/preceding::span[1]</value>
      <webElementGuid>71a82089-c4fb-4aeb-a198-c62b9cbf0b9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FAQs'])[1]/preceding::span[1]</value>
      <webElementGuid>d635f0bd-1037-4d98-97fa-b30e9a134965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='notAdmin']/parent::*</value>
      <webElementGuid>66618d1a-748c-4d8f-8b3a-692c6e06ba76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/a/span</value>
      <webElementGuid>bbaafc02-d8e1-4217-ae63-4c82f0c383e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'notAdmin' or . = 'notAdmin')]</value>
      <webElementGuid>a743ce71-5b30-446f-a4b6-a937e9b56455</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
